name: weather
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  get_it: ^7.7.0
  intl: ^0.19.0
  qweather_icons: ^1.6.0
  weather_animation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
